service: gb-tech-test
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x

functions:
  GetBestLanguages:
    handler: src/functions/get-best-languages/handler.main
    events:
      - http:
          path: /repo-by-languages
          method: get

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
