// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "GB Tech Test Github",
    "version": "1"
  },
  "paths": {
    "/repo-by-languages": {
      "get": {
        "summary": "GetBestLanguages",
        "description": "",
        "tags": [
          "GITHUB"
        ],
        "operationId": "GetBestLanguages.get./repo-by-languages",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetReposByLanguageResponse"
            }
          },
          "405": {
            "description": "Method not allowed",
            "schema": {
              "$ref": "#/definitions/GetReposByLanguageResponse405"
            }
          },
          "default": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/GetReposByLanguageResponseError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "GetReposByLanguageResponse": {
      "properties": {
        "message": {
          "title": "GetReposByLanguageResponse.message",
          "enum": [
            "Success"
          ],
          "type": "string"
        },
        "data": {
          "items": {
            "$ref": "#/definitions/Language",
            "title": "GetReposByLanguageResponse.data.[]"
          },
          "title": "GetReposByLanguageResponse.data",
          "type": "array"
        }
      },
      "required": [
        "message",
        "data"
      ],
      "additionalProperties": false,
      "title": "GetReposByLanguageResponse",
      "type": "object"
    },
    "GetReposByLanguageResponse405": {
      "properties": {
        "message": {
          "title": "GetReposByLanguageResponse405.message",
          "enum": [
            "Method not allowed"
          ],
          "type": "string"
        },
        "data": {
          "title": "GetReposByLanguageResponse405.data",
          "nullable": true
        }
      },
      "required": [
        "message",
        "data"
      ],
      "additionalProperties": false,
      "title": "GetReposByLanguageResponse405",
      "type": "object"
    },
    "GetReposByLanguageResponseError": {
      "properties": {
        "message": {
          "title": "GetReposByLanguageResponseError.message",
          "enum": [
            "message-error"
          ],
          "type": "string"
        },
        "data": {
          "title": "GetReposByLanguageResponseError.data",
          "nullable": true
        }
      },
      "required": [
        "message",
        "data"
      ],
      "additionalProperties": false,
      "title": "GetReposByLanguageResponseError",
      "type": "object"
    },
    "Language": {
      "properties": {
        "id": {
          "title": "Language.id",
          "type": "string"
        },
        "name": {
          "title": "Language.name",
          "type": "string"
        },
        "repos": {
          "items": {
            "$ref": "#/definitions/Repo",
            "title": "Language.repos.[]"
          },
          "title": "Language.repos",
          "type": "array"
        }
      },
      "required": [
        "id",
        "name",
        "repos"
      ],
      "additionalProperties": false,
      "title": "Language",
      "type": "object"
    },
    "Repo": {
      "properties": {
        "githubId": {
          "title": "Repo.githubId",
          "type": "number"
        },
        "name": {
          "title": "Repo.name",
          "type": "string"
        },
        "description": {
          "title": "Repo.description",
          "type": "string"
        },
        "fullName": {
          "title": "Repo.fullName",
          "type": "string"
        },
        "private": {
          "title": "Repo.private",
          "type": "boolean"
        },
        "owner": {
          "$ref": "#/definitions/Owner",
          "title": "Repo.owner"
        },
        "url": {
          "title": "Repo.url",
          "type": "string"
        },
        "contributors": {
          "items": {
            "$ref": "#/definitions/Contributor",
            "title": "Repo.contributors.[]"
          },
          "title": "Repo.contributors",
          "type": "array"
        },
        "homePage": {
          "title": "Repo.homePage",
          "type": "string"
        },
        "stargazers": {
          "title": "Repo.stargazers",
          "type": "number"
        },
        "visibility": {
          "title": "Repo.visibility",
          "type": "string"
        }
      },
      "required": [
        "githubId",
        "name",
        "description",
        "fullName",
        "private",
        "owner",
        "url",
        "contributors",
        "homePage",
        "stargazers",
        "visibility"
      ],
      "additionalProperties": false,
      "title": "Repo",
      "type": "object"
    },
    "Owner": {
      "properties": {
        "name": {
          "title": "Owner.name",
          "type": "string"
        },
        "avatarUrl": {
          "title": "Owner.avatarUrl",
          "type": "string"
        },
        "pageUrl": {
          "title": "Owner.pageUrl",
          "type": "string"
        }
      },
      "required": [
        "name",
        "avatarUrl",
        "pageUrl"
      ],
      "additionalProperties": false,
      "title": "Owner",
      "type": "object"
    },
    "Contributor": {
      "properties": {
        "name": {
          "title": "Contributor.name",
          "type": "string"
        },
        "avatarUrl": {
          "title": "Contributor.avatarUrl",
          "type": "string"
        },
        "pageUrl": {
          "title": "Contributor.pageUrl",
          "type": "string"
        }
      },
      "required": [
        "name",
        "avatarUrl",
        "pageUrl"
      ],
      "additionalProperties": false,
      "title": "Contributor",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};